# Generated by Django 4.1.2 on 2022-11-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
