version: "3.9"

services:
  db:
    env_file:
      - env/.env
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/innotter
    ports:
      - "8000:8000"
    depends_on:
      - db