# Generated by Django 4.1.2 on 2022-11-04 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_page_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="follow_requests",
            field=models.ManyToManyField(
                default=None, related_name="requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
