# Generated by Django 4.1.2 on 2022-11-05 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_post_created_at_post_updated_at_alter_page_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="page",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("57350f3b-5ffb-4314-93a9-9f3a03532f4f"),
                unique=True,
            ),
        ),
    ]
