# Generated by Django 4.1.2 on 2022-11-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_page_is_private_page_is_privatee'),
        ('core', '0011_post_dislikes_post_likes_alter_page_uuid'),
    ]

    operations = [
    ]
