apiVersion: apps/v1
kind: Deployment
metadata:
  name: innotter-deployment
  labels:
    app: innotter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: innotter
  template:
    metadata:
      labels:
        app: innotter
    spec:
      containers:
        - name: innotter-web
          image: 942398500930.dkr.ecr.us-east-1.amazonaws.com/innotter-container-storage:latest-innotter
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: innotter-prod-env
          imagePullPolicy: Always


---


apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: celery
  name: celery-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: innotter
        component: innotter
    spec:
      containers:
      - image: 942398500930.dkr.ecr.us-east-1.amazonaws.com/innotter-container-storage:latest-innotter
        name: innotter-web
        command: [ "/bin/sh","-c" ]
        args: [ "celery -A innotter beat -l info --detach; celery -A innotter worker -l info;" ]
        ports:
          - name: innotter-web
            containerPort: 8000
            protocol: TCP
        envFrom:
          - secretRef:
              name: innotter-prod-env
        imagePullPolicy: Always

---


apiVersion: v1
kind: Service
metadata:
  name: innotter-web-service
spec:
  type: LoadBalancer
  ports:
    - name: innotter-web
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: innotter
