apiVersion: apps/v1
kind: Deployment
metadata:
  name: innotter-deployment
  labels:
    app: innotter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: innotter
  template:
    metadata:
      labels:
        app: innotter
    spec:
      containers:
        - name: innotter-web
          image: 942398500930.dkr.ecr.us-east-1.amazonaws.com/innotter-container-storage:latest-innotter
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: innotter-prod-env


---


apiVersion: v1
kind: Service
metadata:
  name: innotter-web-service
spec:
  type: LoadBalancer
  ports:
    - name: innotter-web
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: innotter
