name: AWS ECR push

on:
  workflow_run:
    workflows: [Django Postgres CI]
    branches: ["main", "dev"]
    types:
      - completed
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      REPOSITORY: ${{ secrets.REPO_NAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REPOSITORY: ${{ env.REPOSITORY }}
      run: |
          docker build -f Dockerfile \
          -t 942398500930.dkr.ecr.us-east-1.amazonaws.com/innotter-container-storage:latest-innotter \
          -t 942398500930.dkr.ecr.us-east-1.amazonaws.com/ \
          innotter-container-storage:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
          .
    - name: Push image
      run: |
        docker push 942398500930.dkr.ecr.us-east-1.amazonaws.com/innotter-container-storage --all-tags
